name: Check
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x
            - name: Just setup
              uses: extractions/setup-just@v2

            - name: Check
              run: just check
