name: Publish
on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Deno
              # uses: denoland/setup-deno@v1
              uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.2
              with:
                  deno-version: v1.x

            - name: Publish
              run: deno publish
